### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-app#1]
~~The blocker for Windows support is being able to get the current folder in Explorer, so it can know where to look for a gulpfile. I'm not sure how to find that on Windows.~~

**Comment by fritx** [comment]
hey I've just forked to support Windows also https://github.com/fritx/gulp-app

**Comment by gutierri** [comment]
Close?
@fritx made the port to Windows on a [repository](https://github.com/fritx/gulp-app)
Or a pull request is welcome in this repository?

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by sindresorhus** [comment]
Closing as this app is now deprecated.
