### ISSUE TITLE
Run `npm install` for the user

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-app#11]
In case they forgot.

I kinda like it, but not sure if it's a good idea or not.

**Comment by clintonhalpin** [comment]
@sindresorhus :+1: on this. 

I could see the gulp app being a tool primarily for designers or people not all that familiar with the CLI. It would make it even easier for those users if it handled installing dependencies and maybe even installing node?

**Comment by sindresorhus** [comment]
Closing as this app is now deprecated.
