### ISSUE TITLE
Doesn't detect gulpfile in open folder

### ISSUE THREAD

**Issue by geekgonecrazy** [sindresorhus/gulp-app#14]
Created as requested.
![screen shot 2014-05-20 at 1 42 46 pm](https://cloud.githubusercontent.com/assets/51996/3031636/c182f43a-e04e-11e3-9709-896e1e77686c.png)
1. started gulp-app
2. opened folder.
3. checked menu / watched output.
4. After bringing the window into focus a couple more times it seemed to get it.

![screen shot 2014-05-20 at 1 46 02 pm](https://cloud.githubusercontent.com/assets/51996/3031665/199cdd16-e04f-11e3-90b5-c43e383de734.png)

After found it listed multiples of my build task.  No additional console logs to associate with behavior. 

Like mentioned elsewhere i'd suggest ditching this method.  Its cool... but doesn't work well.  Doesn't stay locked etc.

**Comment by sindresorhus** [comment]
Closing as this app is now deprecated.
