### ISSUE TITLE
Gulp sub task names are truncated

### ISSUE THREAD

**Issue by kokujin** [sindresorhus/gulp-app#22]
Gulp sub task names are truncated

**Comment by sindresorhus** [comment]
Are you using 0.1.0 or master? Can you show me a screenshot?

**Comment by kokujin** [comment]
I have un-installed Gulp app, so I can't deliver a screen shot, basically, the problem is that I have several tasks that have prefixes like "compress-css-', for example "compress-css-main', "compress-css-mobile' e.t.c, these all show up in the list as "compress-css'

**Comment by sindresorhus** [comment]
Oh, yeah. I'm seeing that too. Just tried master, and it's fixed there.
