### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by modulexcite** [sindresorhus/gulp-app#27]
is this going to be released for the Windows platform? @sindresorhus you're a programming god and you rock, thanks for all the awesome work you do and share with the rest of us.

**Comment by sindresorhus** [comment]
Yes, that was the plan all along, but I just haven't had enough time, even working full-time on open source... Maybe in a month.

**Comment by modulexcite** [comment]
great, look forward to it. thanks.

**Comment by sindresorhus** [comment]
Duplicate of #1
