### ISSUE TITLE
Use HTML5 Notification instead of the `display-notification` module

### ISSUE THREAD

**Issue by zeakd** [sindresorhus/gulp-app#29]
It seems better to use BrowserWindow and html5 Notification instead of displayNotification. It solve #23 and looks better because it shows icon. also for window, linux support.

**Comment by sindresorhus** [comment]
Sure. PR welcome :)

**Comment by zeakd** [comment]
@sindresorhus How about [node-notifier](https://github.com/mikaelbr/node-notifier)?

**Comment by sindresorhus** [comment]
@zeakd I don't really see the point when Electron has it built-in through the browser window.

**Comment by zeakd** [comment]
for OS support. The difference is Electron just can open Chromium based window which have HTML5 Notification API, and node-notifier is an abstraction of some notification systems. [node notifier OS support](https://github.com/mikaelbr/node-notifier#requirements)

**Comment by sindresorhus** [comment]
I'm aware of how it works, but `node-notifier` is, from previous experience, very buggy and I don't see much added value in the extra maintenance overhead when HTML5 notifications solves our specific use-case good enough.

**Comment by sindresorhus** [comment]
Closing as this app is now deprecated.
